[package]
name = "raziel"
version = "0.4.11"
edition = "2021"

[dependencies]
serenity = { version = "0.11.6", default-features = false, features = ["client", "gateway", "default_native_tls", "model", "simd_json"] }
tokio = { version = "1.29.1", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.7.1", features = [ "runtime-tokio-native-tls", "sqlite"] }
os_info = { version = "3.7.0", default-features = false }
chrono = "0.4.26"
libc_alloc = "1.0.4"
string-builder = "0.2.0"
reqwest = "0.11.18"
serde = "1.0.174"
serde_json = "1.0.103"
rand = "0.8.5"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
