[package]
name = "raziel"
version = "0.3.1"
edition = "2021"

[dependencies]
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "default_native_tls", "model", "simd_json"] }
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
os_info = { version = "3.5.1", default-features = false }
chrono = "0.4.23"
rusqlite = "0.28.0"
libc_alloc = "1.0.4"
whois = "0.1.0"
rustc-serialize = "0.3.24"
string-builder = "0.2.0"
reqwest = "0.11.13"
serde = "1.0.152"
serde_json = "1.0.93"
rand = "0.8.5"

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1
panic = "abort"
